package p.f15;
import java.lang.Object;
import p.kc1;
import p.i40;
import java.util.ArrayList;
import p.i70;
import p.we7;
import p.up0;
import p.eq;
import p.vu0;
import p.hd1;
import javax.net.SocketFactory;
import java.lang.String;
import p.co5;
import p.g15;
import p.a15;
import p.ld0;
import java.lang.Iterable;
import java.util.AbstractCollection;
import p.cj0;

public final class f15	// class@00153c from classes.dex
{
    public int A;
    public final int B;
    public final long C;
    public hj2 D;
    public kc1 a;
    public final i40 b;
    public final ArrayList c;
    public final ArrayList d;
    public final up0 e;
    public final boolean f;
    public eq g;
    public boolean h;
    public final boolean i;
    public final vu0 j;
    public a90 k;
    public final hd1 l;
    public final Proxy m;
    public final ProxySelector n;
    public final eq o;
    public SocketFactory p;
    public final SSLSocketFactory q;
    public final X509TrustManager r;
    public final List s;
    public final List t;
    public final HostnameVerifier u;
    public final ld0 v;
    public final ry7 w;
    public int x;
    public int y;
    public int z;

    public void f15(){
       super();
       this.a = new kc1();
       this.b = new i40(3);
       this.c = new ArrayList();
       this.d = new ArrayList();
       this.e = new up0(19, i70.z);
       this.f = true;
       gg1 e = eq.e;
       this.g = e;
       this.h = true;
       this.i = true;
       this.j = vu0.g;
       this.l = hd1.h;
       this.o = e;
       SocketFactory default = SocketFactory.getDefault();
       co5.l(default, "getDefault\(\)");
       this.p = default;
       this.s = g15.W;
       this.t = g15.V;
       this.u = a15.a;
       this.v = ld0.c;
       this.y = 0x2710;
       this.z = 0x2710;
       this.A = 0x2710;
       this.C = 1024;
    }
    public void f15(g15 p0){
       co5.o(p0, "okHttpClient");
       super();
       this.a = p0.a;
       this.b = p0.b;
       cj0.c0(p0.c, this.c);
       cj0.c0(p0.t, this.d);
       this.e = p0.v;
       this.f = p0.w;
       this.g = p0.x;
       this.h = p0.y;
       this.i = p0.z;
       this.j = p0.A;
       this.k = p0.B;
       this.l = p0.C;
       this.m = p0.D;
       this.n = p0.E;
       this.o = p0.F;
       this.p = p0.G;
       this.q = p0.H;
       this.r = p0.I;
       this.s = p0.J;
       this.t = p0.K;
       this.u = p0.L;
       this.v = p0.M;
       this.w = p0.N;
       this.x = p0.O;
       this.y = p0.P;
       this.z = p0.Q;
       this.A = p0.R;
       this.B = p0.S;
       this.C = p0.T;
       this.D = p0.U;
    }
}
