package p.nq0;
import java.lang.Object;
import p.qq0;
import p.pq0;
import p.oq0;
import p.rq0;
import java.util.HashMap;
import p.hq0;
import android.view.ViewGroup$MarginLayoutParams;
import java.lang.Class;
import java.util.Arrays;

public final class nq0	// class@002028 from classes.dex
{
    public int a;
    public final qq0 b;
    public final pq0 c;
    public final oq0 d;
    public final rq0 e;
    public HashMap f;

    public void nq0(){
       super();
       this.b = new qq0();
       this.c = new pq0();
       this.d = new oq0();
       this.e = new rq0();
       this.f = new HashMap();
    }
    public final void a(hq0 p0){
       oq0 k0;
       nq0 td = this.d;
       p0.e = td.h;
       p0.f = td.i;
       p0.g = td.j;
       p0.h = td.k;
       p0.i = td.l;
       p0.j = td.m;
       p0.k = td.n;
       p0.l = td.o;
       p0.m = td.p;
       p0.n = td.q;
       p0.o = td.r;
       p0.s = td.s;
       p0.t = td.t;
       p0.u = td.u;
       p0.v = td.v;
       p0.leftMargin = td.F;
       p0.rightMargin = td.G;
       p0.topMargin = td.H;
       p0.bottomMargin = td.I;
       p0.A = td.R;
       p0.B = td.Q;
       p0.x = td.N;
       p0.z = td.P;
       p0.E = td.w;
       p0.F = td.x;
       p0.p = td.z;
       p0.q = td.A;
       p0.r = td.B;
       p0.G = td.y;
       p0.T = td.C;
       p0.U = td.D;
       p0.I = td.T;
       p0.H = td.U;
       p0.K = td.W;
       p0.J = td.V;
       p0.W = td.l0;
       p0.X = td.m0;
       p0.L = td.X;
       p0.M = td.Y;
       p0.P = td.Z;
       p0.Q = td.a0;
       p0.N = td.b0;
       p0.O = td.c0;
       p0.R = td.d0;
       p0.S = td.e0;
       p0.V = td.E;
       p0.c = td.f;
       p0.a = td.d;
       p0.b = td.e;
       p0.width = td.b;
       p0.height = td.c;
       if ((k0 = td.k0) != null) {
          p0.Y = k0;
       }
       p0.Z = td.o0;
       p0.setMarginStart(td.K);
       p0.setMarginEnd(td.J);
       p0.a();
       return;
    }
    public final Object clone(){
       oq0 i0;
       nq0 onq0 = new nq0();
       nq0 d = onq0.d;
       d.getClass();
       nq0 td = this.d;
       d.a = td.a;
       d.b = td.b;
       d.c = td.c;
       d.d = td.d;
       d.e = td.e;
       d.f = td.f;
       d.g = td.g;
       d.h = td.h;
       d.i = td.i;
       d.j = td.j;
       d.k = td.k;
       d.l = td.l;
       d.m = td.m;
       d.n = td.n;
       d.o = td.o;
       d.p = td.p;
       d.q = td.q;
       d.r = td.r;
       d.s = td.s;
       d.t = td.t;
       d.u = td.u;
       d.v = td.v;
       d.w = td.w;
       d.x = td.x;
       d.y = td.y;
       d.z = td.z;
       d.A = td.A;
       d.B = td.B;
       d.C = td.C;
       d.D = td.D;
       d.E = td.E;
       d.F = td.F;
       d.G = td.G;
       d.H = td.H;
       d.I = td.I;
       d.J = td.J;
       d.K = td.K;
       d.L = td.L;
       d.M = td.M;
       d.N = td.N;
       d.O = td.O;
       d.P = td.P;
       d.Q = td.Q;
       d.R = td.R;
       d.S = td.S;
       d.T = td.T;
       d.U = td.U;
       d.V = td.V;
       d.W = td.W;
       d.X = td.X;
       d.Y = td.Y;
       d.Z = td.Z;
       d.a0 = td.a0;
       d.b0 = td.b0;
       d.c0 = td.c0;
       d.d0 = td.d0;
       d.e0 = td.e0;
       d.f0 = td.f0;
       d.g0 = td.g0;
       d.h0 = td.h0;
       d.k0 = td.k0;
       d.i0 = ((i0 = td.i0) != null && td.j0 == null)? Arrays.copyOf(i0, i0.length): null;
       d.j0 = td.j0;
       d.l0 = td.l0;
       d.m0 = td.m0;
       d.n0 = td.n0;
       d.o0 = td.o0;
       d = onq0.c;
       d.getClass();
       td = this.c;
       td.getClass();
       d.a = td.a;
       d.c = td.c;
       d.e = td.e;
       d.d = td.d;
       d = onq0.b;
       d.getClass();
       td = this.b;
       td.getClass();
       d.a = td.a;
       d.c = td.c;
       d.d = td.d;
       d.b = td.b;
       d = onq0.e;
       d.getClass();
       td = this.e;
       td.getClass();
       d.a = td.a;
       d.b = td.b;
       d.c = td.c;
       d.d = td.d;
       d.e = td.e;
       d.f = td.f;
       d.g = td.g;
       d.h = td.h;
       d.i = td.i;
       d.j = td.j;
       d.k = td.k;
       d.l = td.l;
       d.m = td.m;
       onq0.a = this.a;
       return onq0;
    }
}
