package p.ua;
import p.sc;
import p.he2;
import java.lang.Object;
import p.tt0;
import com.spotify.allboarding.contextualaudio.presentation.ContextualAudioFragment;
import java.lang.Class;
import p.j8;
import p.pt0;
import p.wt0;
import p.ot0;
import p.tm5;
import p.v26;
import p.co5;
import p.kf6;
import io.reactivex.rxjava3.core.Observable;
import p.hj4;
import p.x12;
import io.reactivex.rxjava3.core.Scheduler;
import p.r61;
import p.ab7;
import p.ds3;
import p.ql6;
import com.spotify.allboarding.allboardingimpl.skip.SkipDialogFragment;
import p.bb7;
import p.ez3;
import p.w76;
import com.spotify.allboarding.allboardingimpl.search.SearchFragment;
import p.fh5;
import p.v76;
import p.fb4;
import p.gj4;
import p.q77;
import p.si4;
import p.y9;
import p.zg0;
import p.y86;
import p.wv6;
import com.spotify.allboarding.allboardingimpl.presentation.summary.SummaryFragment;
import p.vv6;
import p.tc;
import p.oo0;
import p.va;
import com.spotify.allboarding.allboardingimpl.mobius.AllBoardingFragment;
import p.es;
import p.ra;
import p.qa;
import p.ub;
import p.v9;
import p.zk;
import p.gg1;
import com.spotify.allboarding.entrypointlite.AllboardingFollowManagerImpl;
import p.fj4;
import com.spotify.allboarding.entrypointlite.AllboardingDoneImpl;
import p.qb;
import p.y37;
import p.cp3;
import p.b65;
import p.t55;
import p.fz3;
import p.dz3;
import p.yy3;

public final class ua implements sc	// class@002877 from classes.dex
{
    public final int a;
    public final he2 b;

    public void ua(he2 p0,int p1){
       this.a = p1;
       this.b = p0;
       super();
    }
    public final void a(Object p0){
       ds3 uods3;
       gj4 ogj4;
       y9 oy9;
       Scheduler scheduler;
       oo0 ooo0;
       Scheduler scheduler3;
       boolean b = false;
       ua tb = this.b;
       switch (this.a){
           case 0:
             va a = tb.a;
             a.getClass();
             p0.getClass();
             es uoes = new es(a);
             uods3 = uoes.a.j.get();
             co5.m(uods3);
             bb7 a1 = new bb7(uods3);
             ogj4 = uoes.a.g.get();
             co5.m(ogj4);
             p0.b = ogj4;
             oy9 = uoes.a.a.get();
             co5.m(oy9);
             zk ozk = new zk(oy9, new gg1());
             v26 obj = uoes.a.e.get();
             co5.m(obj);
             Object obj1 = uoes.a.b.get();
             co5.m(obj1);
             uods3 = uoes.a.j.get();
             co5.m(uods3);
             bb7 uobb7 = new bb7(uods3);
             Object obj2 = uoes.a.c.get();
             co5.m(obj2);
             y37 oy37 = uoes.a.h.get();
             co5.m(oy37);
             qb oqb = new qb(oy37);
             Object obj3 = uoes.a.d.get();
             co5.m(obj3);
             Object obj4 = uoes.a.k.get();
             co5.m(obj4);
             v9 v12 = new v9(ozk, obj, obj1, uobb7, obj2, oqb, obj3, obj4);
             scheduler = uoes.a.l.get();
             co5.m(scheduler);
             Scheduler scheduler1 = uoes.a.m.get();
             co5.m(scheduler1);
             obj = uoes.a.q.get();
             co5.m(obj);
             p0.c = new ub(v12, scheduler, scheduler1, obj);
             b65 uob65 = uoes.a.o.get();
             co5.m(uob65);
             p0.v = uob65;
             p0.w = uoes.i.get();
             co5.m(uoes.a.l.get());
             ooo0 = uoes.a.i.get();
             co5.m(ooo0);
             p0 = new tc(b, ooo0);
             return;
           case 1:
             wv6 a2 = tb.a;
             a2.getClass();
             p0.getClass();
             r61 or61 = a2.a.get();
             co5.m(or61);
             p0.b = or61;
             Scheduler scheduler2 = a2.b.get();
             co5.m(scheduler2);
             p0.c = scheduler2;
             ooo0 = a2.c.get();
             co5.m(ooo0);
             p0.t = new tc(b, ooo0);
             return;
           case 2:
             w76 a3 = tb.a;
             a3.getClass();
             p0.getClass();
             v76 h = a3.h;
             uods3 = h.get();
             co5.m(uods3);
             p0.c = new fh5(uods3, new fb4());
             ogj4 = a3.e.get();
             co5.m(ogj4);
             p0.t = ogj4;
             r61 or611 = a3.f.get();
             co5.m(or611);
             p0.v = or611;
             q77 oq77 = a3.g.get();
             co5.m(oq77);
             p0.w = oq77;
             ds3 uods31 = h.get();
             co5.m(uods31);
             fh5 uofh5 = new fh5(uods31, new fb4());
             oy9 = a3.a.get();
             co5.m(oy9);
             zg0 ozg0 = a3.d.get();
             co5.m(ozg0);
             si4 osi4 = new si4(oy9, ozg0);
             scheduler = a3.c.get();
             co5.m(scheduler);
             scheduler3 = a3.b.get();
             co5.m(scheduler3);
             p0.x = new y86(uofh5, osi4, scheduler, scheduler3);
             return;
           case 3:
             ql6 a4 = tb.a;
             a4.getClass();
             p0.getClass();
             ds3 uods32 = a4.a.get();
             co5.m(uods32);
             p0.I = new bb7(uods32);
             return;
           case 4:
             tt0 a5 = tb.a;
             a5.getClass();
             p0.getClass();
             j8 oj8 = new j8(a5);
             v26 ov26 = oj8.b.f.get();
             co5.m(ov26);
             Observable observable = oj8.b.c.get();
             co5.m(observable);
             hj4 ohj4 = oj8.b.g.get();
             co5.m(ohj4);
             kf6 okf6 = new kf6(observable, ohj4);
             p0.b = new wt0(ov26, okf6, new x12(oj8.v));
             scheduler3 = oj8.b.d.get();
             co5.m(scheduler3);
             p0.c = scheduler3;
             r61 or612 = oj8.b.e.get();
             co5.m(or612);
             p0.t = or612;
             ds3 uods33 = oj8.b.b.get();
             co5.m(uods33);
             p0.v = new ab7(uods33);
             return;
           default:
             fz3 a6 = tb.a;
             a6.getClass();
             p0.getClass();
             yy3 oyy3 = a6.a.get();
             co5.m(oyy3);
             p0.J = oyy3;
             return;
       }
    }
}
