package p.wm;
import p.od;
import android.app.Application;
import p.sm;
import p.c96;
import p.zg5;
import p.np3;
import p.t2;
import p.hv6;
import p.an5;
import com.spotify.mobius.rx3.RxMobius$SubtypeEffectHandlerBuilder;
import com.spotify.mobius.rx3.RxMobius;
import p.um;
import p.e66;
import java.lang.Class;
import io.reactivex.rxjava3.core.ObservableTransformer;
import p.q56;
import p.w56;
import p.f66;
import p.x56;
import p.a66;
import p.v56;
import p.c66;
import p.t56;
import p.bm;
import p.xo0;
import com.spotify.mobius.rx3.RxConnectables;
import p.kd7;
import p.lb4;
import p.mi;
import java.lang.String;
import p.ms3;
import p.qb4;
import android.os.Bundle;
import androidx.fragment.app.Fragment;
import android.os.BaseBundle;
import p.xe7;
import p.i77;
import java.lang.Boolean;
import p.lr;
import java.lang.Object;
import p.sb4;

public final class wm extends od	// class@002b6a from classes.dex
{
    public final an5 A;
    public final an5 B;
    public final an5 C;
    public final an5 D;
    public final an5 E;
    public final sb4 F;
    public final c96 v;
    public final zg5 w;
    public final np3 x;
    public final t2 y;
    public final hv6 z;

    public void wm(Application p0,sm p1,c96 p2,zg5 p3,np3 p4,t2 p5,hv6 p6){
       Bundle arguments;
       super(p0);
       this.A = new an5();
       this.B = new an5();
       this.C = new an5();
       this.D = new an5();
       this.E = new an5();
       this.v = p2;
       this.w = p3;
       this.x = p4;
       this.y = p5;
       this.z = p6;
       RxMobius$SubtypeEffectHandlerBuilder subtypeEffec = RxMobius.a();
       subtypeEffec.g(e66.class, new um(this, 7));
       int i = 2;
       subtypeEffec.g(q56.class, new um(this, i));
       int i1 = 4;
       subtypeEffec.g(w56.class, new um(this, i1));
       subtypeEffec.g(f66.class, new um(this, 1));
       subtypeEffec.g(x56.class, new um(this, 3));
       subtypeEffec.g(a66.class, new um(this, 6));
       subtypeEffec.g(v56.class, new um(this, 0));
       subtypeEffec.g(c66.class, new um(this, 5));
       subtypeEffec.g(t56.class, new um(this, 8));
       lb4 olb4 = mi.A(new bm(i1), RxConnectables.a(subtypeEffec.h())).d(new bm(i)).e(ms3.i("AssistedCurationSearch"));
       String str = ((arguments = p1.getArguments()) == null)? null: arguments.getString("spotify.fragment.argument.PLAYLIST_URI");
       i77 oi77 = new i77();
       oi77.a = Boolean.FALSE;
       oi77.d = null;
       oi77.b = null;
       oi77.e = null;
       oi77.f = null;
       oi77.c = xe7.J(str);
       this.F = mi.g(olb4, oi77.g().a(1));
       return;
    }
}
