package com.spotify.eventsender.eventsender.a;
import p.wu1;
import android.content.Context;
import p.uu1;
import p.l56;
import p.ou1;
import io.reactivex.rxjava3.core.Observable;
import p.t00;
import java.lang.Object;
import p.n56;
import p.ce7;
import p.g54;
import p.vx5;
import com.spotify.eventsender.eventsender.gabo.c;
import com.spotify.eventsender.eventsender.gabo.a;
import p.yh2;
import p.hs3;
import com.spotify.eventsender.eventsender.EventSenderDatabase;
import java.lang.Class;
import java.lang.String;
import p.vy5;
import p.b17;
import p.ka4;
import p.lq7;
import p.xy5;
import p.li5;
import p.oe7;
import p.na6;
import p.aw1;
import p.lv1;
import p.i70;
import p.vf;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import p.cu1;
import java.util.Map;
import p.uv1;
import java.util.ArrayList;
import java.util.Collection;
import p.ia5;
import p.t67;
import p.u44;
import p.si4;
import p.o11;
import p.qo5;
import p.lf1;
import p.of1;
import p.gv1;
import p.dy1;
import p.yu1;
import p.or7;
import p.fv1;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import p.vw1;
import java.util.concurrent.Executor;
import p.nc2;
import p.s36;
import p.am0;
import io.reactivex.rxjava3.core.Scheduler;
import p.vu1;
import p.kj4;
import p.lp;
import com.google.common.collect.c;
import p.w51;
import p.ys5;
import p.i77;
import io.reactivex.rxjava3.disposables.Disposable;

public final class a implements wu1	// class@0008ad from classes.dex
{
    public final nc2 a;
    public final vu1 b;
    public final l56 c;
    public final ia5 d;
    public final of1 e;
    public final na6 f;
    public final i70 g;
    public final n56 h;
    public boolean i;

    public void a(Context p0,uu1 p1,l56 p2,ou1 p3,Observable p4,t00 p5){
       a uoa = this;
       Context uContext = p0;
       l56 ol56 = p2;
       super();
       Context applicationC = p0.getApplicationContext();
       uoa.c = ol56;
       n56 on56 = new n56();
       uoa.h = on56;
       ce7 uoce7 = new ce7(p4, on56);
       g54 og54 = new g54(new vx5(uContext));
       l56 b = ol56.b;
       a uoa1 = new a(new c(p1), new yh2(), b);
       vy5 ovy5 = b17.i(uContext, EventSenderDatabase.class, "event-sender.db");
       ka4[] oka4Array = new ka4[]{new lq7(2),new lq7(3),new lq7(4),new lq7(5),new lq7(1, null)};
       ovy5.a(oka4Array);
       ovy5.l = false;
       ovy5.m = true;
       xy5 oxy5 = ovy5.b();
       oe7 ooe7 = new oe7(applicationC, 9);
       uoa.f = new na6(ooe7, new li5(og54), new aw1(oxy5.t(), og54));
       uoa.g = new i70();
       vf v13 = new vf(applicationC, og54, ol56.b, ooe7, new li5(og54), on56);
       HashMap hashMap = new HashMap();
       Iterator iterator = ol56.a.iterator();
       while (iterator.hasNext()) {
          cu1 uocu1 = iterator.next();
          hashMap.put(uocu1.a(), uocu1);
       }
       v13.b.putAll(hashMap);
       uv1 ouv1 = hashMap;
       uoa.d = new ia5(b, uoce7, uoa.h);
       l56 b1 = uoa.c.b;
       t67 iterator1 = new t67(uoa.f, oxy5.t(), new uv1(new ArrayList(v13.b.values())), oxy5.v(), ooe7, b1, uoa.g, 6);
       i77 u44 hashMap1 = new u44(25, b1);
       si4 og541 = new si4(b1);
       o11 oo11 = b1;
       lf1 olf1 = oka4Array;
       lf1 olf11 = new lf1(uContext, uoa.c.b);
       uoa.e = new of1(olf11, uoa.c.b, p5);
       dy1 uody1 = v8;
       dy1 yu1 uody11 = new dy1(10);
       yu1 oyu1 = uody11;
       uody11 = new yu1(uoa1, 0);
       or7 oor7 = uody11;
       or7 uody111 = new or7(8);
       gv1 uContext1 = new gv1(oxy5.u(), oo11, p3, olf1, uody1, uoa.f, oxy5.t(), ouv1, ol56.d, oyu1, iterator, oor7, uoa.c.b, uoa.g, uoa.h, ol56.c);
       gv1 ogv1 = uContext;
       nc2 on561 = new nc2(iterator, p3, olf11, og541, new o11(new u44(oxy5.w()), uoa.c.b), uoa.c.b, new uv1(23), uoa.g, new vw1(Executors.newSingleThreadExecutor(), false, false), s36.b, ol56.d, new am0(18, uoa));
       uoa.a = on56;
       kj4 ol561 = new kj4(oxy5.v(), hashMap1, new yu1(uoa1, 1), uoa.c.b);
       lp iterator2 = new lp(oxy5.v(), hashMap1, new yu1(uoa1, 2), uoa.c.b, p3);
       Object[] objArray = new Object[]{ogv1,ol561,iterator};
       w51.e(3, objArray);
       hashMap1 = new i77(oxy5.v(), oxy5.t(), ooe7, uoa.c.b, on56);
       uoa.b = new vu1(c.m(3, objArray), hashMap1, uoa.c.b, olf11);
       return;
    }
    public final void a(){
       a td = this.d;
       _monitor_enter(td);
       if (!td.d.isDisposed()) {
          td.d.dispose();
       }
       _monitor_exit(td);
       this.d.a(this.b);
       return;
    }
}
